In [1]:
import pandas as pd

In [2]:
file_path = "/Volumes/Engineering/Database/HMCorp/java/train.jsonl"
hmcorp = pd.read_json(file_path, lines=True)

In [3]:
srcml = pd.read_csv("../data/scg_features.csv")

In [4]:
srcml["label"] = 1 - srcml["label"]
srcml.head()

,filename,index,label,num_nodes,num_edges,num_self_loops,graph_density,num_cycles,sum_degree,avg_degree,max_degree,min_degree,median_degree,avg_in_degree,avg_out_degree
0,gj000000_ai.xml,0,0,181,350,31,0.010743,170,762,4.209945,19,1,4.0,2.104972,2.104972
1,gj000000_human.xml,0,1,135,254,14,0.014041,120,536,3.970370,13,1,3.0,1.985185,1.985185
2,gj000001_ai.xml,1,0,104,200,18,0.018671,97,436,4.192308,14,1,4.0,2.096154,2.096154
3,gj000001_human.xml,1,1,31,54,7,0.058065,24,122,3.935484,8,1,4.0,1.967742,1.967742
4,gj000002_ai.xml,2,0,60,107,13,0.030226,48,240,4.000000,10,1,4.0,2.000000,2.000000

In [5]:
srcml["id"] =  srcml["filename"].str.split("_").str[0]
srcml.head()

,filename,index,label,num_nodes,num_edges,num_self_loops,graph_density,num_cycles,sum_degree,avg_degree,max_degree,min_degree,median_degree,avg_in_degree,avg_out_degree,id
0,gj000000_ai.xml,0,0,181,350,31,0.010743,170,762,4.209945,19,1,4.0,2.104972,2.104972,gj000000
1,gj000000_human.xml,0,1,135,254,14,0.014041,120,536,3.970370,13,1,3.0,1.985185,1.985185,gj000000
2,gj000001_ai.xml,1,0,104,200,18,0.018671,97,436,4.192308,14,1,4.0,2.096154,2.096154,gj000001
3,gj000001_human.xml,1,1,31,54,7,0.058065,24,122,3.935484,8,1,4.0,1.967742,1.967742,gj000001
4,gj000002_ai.xml,2,0,60,107,13,0.030226,48,240,4.000000,10,1,4.0,2.000000,2.000000,gj000002

In [6]:
srcml.columns

Index(['filename', 'index', 'label', 'num_nodes', 'num_edges',
       'num_self_loops', 'graph_density', 'num_cycles', 'sum_degree',
       'avg_degree', 'max_degree', 'min_degree', 'median_degree',
       'avg_in_degree', 'avg_out_degree', 'id'],
      dtype='str')

In [7]:
output = pd.read_csv("../data/hmcorp_xml.csv")

print("Shape of output:", output.shape)
print("Shape of srcml:", srcml.shape)

print(srcml.columns)
print(output.columns)

Shape of output: (355736, 5)
Shape of srcml: (355736, 16)
Index(['filename', 'index', 'label', 'num_nodes', 'num_edges',
       'num_self_loops', 'graph_density', 'num_cycles', 'sum_degree',
       'avg_degree', 'max_degree', 'min_degree', 'median_degree',
       'avg_in_degree', 'avg_out_degree', 'id'],
      dtype='str')
Index(['id', 'code', 'label', 'language', 'xml'], dtype='str')

In [8]:
merged = pd.merge(output, srcml, on="id", how="inner")
print("Shape of merged:", merged.shape)
print("Head of merged:")
print(merged.head())

Shape of merged: (711472, 20)
Head of merged:
         id                                               code  label_x  \
0  gj235730  public Object readValue(Object value) {\n    /...        1
1  gj235730  public Object readValue(Object value) {\n    /...        1
2  gj235730  private OptionKindAndValue readKindAndValue() ...        0
3  gj235730  private OptionKindAndValue readKindAndValue() ...        0
4  gj164536  public <U> CompletableFuture<U> thenComposeAsy...        1

  language                                                xml  \
0     java  <?xml version="1.0" encoding="UTF-8" standalon...
1     java  <?xml version="1.0" encoding="UTF-8" standalon...
2     java  <?xml version="1.0" encoding="UTF-8" standalon...
3     java  <?xml version="1.0" encoding="UTF-8" standalon...
4     java  <?xml version="1.0" encoding="UTF-8" standalon...

             filename   index  label_y  num_nodes  num_edges  num_self_loops  \
0  gj235730_human.xml  235730        1        194        380              23
1     gj235730_ai.xml  235730        0        227        436              49
2  gj235730_human.xml  235730        1        194        380              23
3     gj235730_ai.xml  235730        0        227        436              49
4     gj164536_ai.xml  164536        0         45         78               9

   graph_density  num_cycles  sum_degree  avg_degree  max_degree  min_degree  \
0       0.010149         187         806    4.154639          13           1
1       0.008499         210         970    4.273128          15           1
2       0.010149         187         806    4.154639          13           1
3       0.008499         210         970    4.273128          15           1
4       0.039394          34         174    3.866667          12           1

   median_degree  avg_in_degree  avg_out_degree
0            4.0       2.077320        2.077320
1            4.0       2.136564        2.136564
2            4.0       2.077320        2.077320
3            4.0       2.136564        2.136564
4            3.0       1.933333        1.933333

In [9]:
print("output id duplicates:", output['id'].duplicated().sum())
print("srcml id duplicates:", srcml['id'].duplicated().sum())

output id duplicates: 177868
srcml id duplicates: 177868

In [10]:
basic_ml = pd.merge(output, srcml, on=["id", "label"], how="inner")
print(basic_ml.shape)

(355736, 19)

In [11]:
# Check if id + label combination is unique in both files
print("output id+label duplicates:", output.duplicated(subset=["id", "label"]).sum())
print("srcml id+label duplicates:", srcml.duplicated(subset=["id", "label"]).sum())

output id+label duplicates: 0
srcml id+label duplicates: 0

In [13]:
basic_ml.columns

Index(['id', 'code', 'label', 'language', 'xml', 'filename', 'index',
       'num_nodes', 'num_edges', 'num_self_loops', 'graph_density',
       'num_cycles', 'sum_degree', 'avg_degree', 'max_degree', 'min_degree',
       'median_degree', 'avg_in_degree', 'avg_out_degree'],
      dtype='str')

In [14]:
basic_ml.iloc[0]

id                                                         gj235730
code              public Object readValue(Object value) {\n    /...
label                                                             1
language                                                       java
xml               <?xml version="1.0" encoding="UTF-8" standalon...
filename                                         gj235730_human.xml
index                                                        235730
num_nodes                                                       194
num_edges                                                       380
num_self_loops                                                   23
graph_density                                              0.010149
num_cycles                                                      187
sum_degree                                                      806
avg_degree                                                 4.154639
max_degree                                                       13
min_degree                                                        1
median_degree                                                   4.0
avg_in_degree                                               2.07732
avg_out_degree                                              2.07732
Name: 0, dtype: object

In [15]:
basic_ml.to_csv("../data/hmcorp_srcml.csv", index=False)