In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../java.csv")

In [4]:
df.columns

Index(['language', 'code', 'label'], dtype='str')

In [5]:
df.iloc[0]

language                                                 java
code        private void registerObject(DigitalObject obj)...
label                                                       0
Name: 0, dtype: object

In [14]:
df.head()

  language                                               code  label
0     java  private void registerObject(DigitalObject obj)...      0
1     java  public void addField(int sourceField, int dest...      1
2     java  @Nonnull\n  public JSFormatter outdentAlways (...      0
3     java  public boolean onMove(int nIDMoveCommand)\n   ...      0
4     java  public static long safeMultiply(long a, long b...      0

In [6]:
file_path = "/Volumes/Engineering/Database/HMCorp/java/train.jsonl"
df2 = pd.read_json(file_path, lines=True)

In [7]:
df2.iloc[0]

index                                                gj235730
code        public Object readValue(Object value) {\n    /...
contrast    private OptionKindAndValue readKindAndValue() ...
label                                                       1
Name: 0, dtype: object

In [8]:
features = pd.read_csv("../scg_features.csv")

In [11]:
features["filename"]

0            gj000000_ai.xml
1         gj000000_human.xml
2            gj000001_ai.xml
3         gj000001_human.xml
4            gj000002_ai.xml
                 ...
355731    gj275464_human.xml
355732       gj275465_ai.xml
355733    gj275465_human.xml
355734       gj275466_ai.xml
355735    gj275466_human.xml
Name: filename, Length: 355736, dtype: str

In [12]:
features.columns

Index(['filename', 'index', 'label', 'num_nodes', 'num_edges',
       'num_self_loops', 'graph_density', 'num_cycles', 'sum_degree',
       'avg_degree', 'max_degree', 'min_degree', 'median_degree',
       'avg_in_degree', 'avg_out_degree'],
      dtype='str')

In [13]:
features.head()

,filename,index,label,num_nodes,num_edges,num_self_loops,graph_density,num_cycles,sum_degree,avg_degree,max_degree,min_degree,median_degree,avg_in_degree,avg_out_degree
0,gj000000_ai.xml,0,1,181,350,31,0.010743,170,762,4.209945,19,1,4.0,2.104972,2.104972
1,gj000000_human.xml,0,0,135,254,14,0.014041,120,536,3.970370,13,1,3.0,1.985185,1.985185
2,gj000001_ai.xml,1,1,104,200,18,0.018671,97,436,4.192308,14,1,4.0,2.096154,2.096154
3,gj000001_human.xml,1,0,31,54,7,0.058065,24,122,3.935484,8,1,4.0,1.967742,1.967742
4,gj000002_ai.xml,2,1,60,107,13,0.030226,48,240,4.000000,10,1,4.0,2.000000,2.000000

In [ ]:
features["label"] = 1 - features["label"]

TypeError: Invalid value '0' for dtype 'int64'